[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html"
    X-Frame-Options = "ALLOW-FROM https://web.telegram.org/"
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline';" 